# Generated by Django 4.1.2 on 2022-11-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
