# Generated by Django 4.1.2 on 2022-11-18 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_no',
            field=models.CharField(max_length=13, validators=[django.core.validators.MaxLengthValidator(13, message='As per ISBN standard, all ISBNs are 13-digits long.'), django.core.validators.MinLengthValidator(13, message='As per ISBN standard, all ISBNs are 13-digits long.')], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
