# Generated by Django 4.1.2 on 2022-11-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_book_issue_id_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_issue_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
